import { isLikelySameString } from "./utils.ts";

type Country = {
  country: string;
  "alpha-2": string;
  "alpha-3": string;
  "numeric-code": number;
  latitude: number;
  longitude: number;
};

const COUNTRIES: Country[] = [
  {
    country: "Afghanistan",
    "alpha-2": "AF",
    "alpha-3": "AFG",
    "numeric-code": 4,
    latitude: 33,
    longitude: 65,
  },
  {
    country: "Albania",
    "alpha-2": "AL",
    "alpha-3": "ALB",
    "numeric-code": 8,
    latitude: 41,
    longitude: 20,
  },
  {
    country: "Algeria",
    "alpha-2": "DZ",
    "alpha-3": "DZA",
    "numeric-code": 12,
    latitude: 28,
    longitude: 3,
  },
  {
    country: "American Samoa",
    "alpha-2": "AS",
    "alpha-3": "ASM",
    "numeric-code": 16,
    latitude: -14.3333,
    longitude: -170,
  },
  {
    country: "Andorra",
    "alpha-2": "AD",
    "alpha-3": "AND",
    "numeric-code": 20,
    latitude: 42.5,
    longitude: 1.6,
  },
  {
    country: "Angola",
    "alpha-2": "AO",
    "alpha-3": "AGO",
    "numeric-code": 24,
    latitude: -12.5,
    longitude: 18.5,
  },
  {
    country: "Anguilla",
    "alpha-2": "AI",
    "alpha-3": "AIA",
    "numeric-code": 660,
    latitude: 18.25,
    longitude: -63.1667,
  },
  {
    country: "Antarctica",
    "alpha-2": "AQ",
    "alpha-3": "ATA",
    "numeric-code": 10,
    latitude: -90,
    longitude: 0,
  },
  {
    country: "Antigua and Barbuda",
    "alpha-2": "AG",
    "alpha-3": "ATG",
    "numeric-code": 28,
    latitude: 17.05,
    longitude: -61.8,
  },
  {
    country: "Argentina",
    "alpha-2": "AR",
    "alpha-3": "ARG",
    "numeric-code": 32,
    latitude: -34,
    longitude: -64,
  },
  {
    country: "Armenia",
    "alpha-2": "AM",
    "alpha-3": "ARM",
    "numeric-code": 51,
    latitude: 40,
    longitude: 45,
  },
  {
    country: "Aruba",
    "alpha-2": "AW",
    "alpha-3": "ABW",
    "numeric-code": 533,
    latitude: 12.5,
    longitude: -69.9667,
  },
  {
    country: "Australia",
    "alpha-2": "AU",
    "alpha-3": "AUS",
    "numeric-code": 36,
    latitude: -27,
    longitude: 133,
  },
  {
    country: "Austria",
    "alpha-2": "AT",
    "alpha-3": "AUT",
    "numeric-code": 40,
    latitude: 47.3333,
    longitude: 13.3333,
  },
  {
    country: "Azerbaijan",
    "alpha-2": "AZ",
    "alpha-3": "AZE",
    "numeric-code": 31,
    latitude: 40.5,
    longitude: 47.5,
  },
  {
    country: "Bahamas",
    "alpha-2": "BS",
    "alpha-3": "BHS",
    "numeric-code": 44,
    latitude: 24.25,
    longitude: -76,
  },
  {
    country: "Bahrain",
    "alpha-2": "BH",
    "alpha-3": "BHR",
    "numeric-code": 48,
    latitude: 26,
    longitude: 50.55,
  },
  {
    country: "Bangladesh",
    "alpha-2": "BD",
    "alpha-3": "BGD",
    "numeric-code": 50,
    latitude: 24,
    longitude: 90,
  },
  {
    country: "Barbados",
    "alpha-2": "BB",
    "alpha-3": "BRB",
    "numeric-code": 52,
    latitude: 13.1667,
    longitude: -59.5333,
  },
  {
    country: "Belarus",
    "alpha-2": "BY",
    "alpha-3": "BLR",
    "numeric-code": 112,
    latitude: 53,
    longitude: 28,
  },
  {
    country: "Belgium",
    "alpha-2": "BE",
    "alpha-3": "BEL",
    "numeric-code": 56,
    latitude: 50.8333,
    longitude: 4,
  },
  {
    country: "Belize",
    "alpha-2": "BZ",
    "alpha-3": "BLZ",
    "numeric-code": 84,
    latitude: 17.25,
    longitude: -88.75,
  },
  {
    country: "Benin",
    "alpha-2": "BJ",
    "alpha-3": "BEN",
    "numeric-code": 204,
    latitude: 9.5,
    longitude: 2.25,
  },
  {
    country: "Bermuda",
    "alpha-2": "BM",
    "alpha-3": "BMU",
    "numeric-code": 60,
    latitude: 32.3333,
    longitude: -64.75,
  },
  {
    country: "Bhutan",
    "alpha-2": "BT",
    "alpha-3": "BTN",
    "numeric-code": 64,
    latitude: 27.5,
    longitude: 90.5,
  },
  {
    country: "Bolivia",
    "alpha-2": "BO",
    "alpha-3": "BOL",
    "numeric-code": 68,
    latitude: -17,
    longitude: -65,
  },
  {
    country: "Bosnia and Herzegovina",
    "alpha-2": "BA",
    "alpha-3": "BIH",
    "numeric-code": 70,
    latitude: 44,
    longitude: 18,
  },
  {
    country: "Botswana",
    "alpha-2": "BW",
    "alpha-3": "BWA",
    "numeric-code": 72,
    latitude: -22,
    longitude: 24,
  },
  {
    country: "Bouvet Island",
    "alpha-2": "BV",
    "alpha-3": "BVT",
    "numeric-code": 74,
    latitude: -54.4333,
    longitude: 3.4,
  },
  {
    country: "Brazil",
    "alpha-2": "BR",
    "alpha-3": "BRA",
    "numeric-code": 76,
    latitude: -10,
    longitude: -55,
  },
  {
    country: "British Indian Ocean Territory",
    "alpha-2": "IO",
    "alpha-3": "IOT",
    "numeric-code": 86,
    latitude: -6,
    longitude: 71.5,
  },
  {
    country: "Brunei",
    "alpha-2": "BN",
    "alpha-3": "BRN",
    "numeric-code": 96,
    latitude: 4.5,
    longitude: 114.6667,
  },
  {
    country: "Bulgaria",
    "alpha-2": "BG",
    "alpha-3": "BGR",
    "numeric-code": 100,
    latitude: 43,
    longitude: 25,
  },
  {
    country: "Burkina Faso",
    "alpha-2": "BF",
    "alpha-3": "BFA",
    "numeric-code": 854,
    latitude: 13,
    longitude: -2,
  },
  {
    country: "Burundi",
    "alpha-2": "BI",
    "alpha-3": "BDI",
    "numeric-code": 108,
    latitude: -3.5,
    longitude: 30,
  },
  {
    country: "Cambodia",
    "alpha-2": "KH",
    "alpha-3": "KHM",
    "numeric-code": 116,
    latitude: 13,
    longitude: 105,
  },
  {
    country: "Cameroon",
    "alpha-2": "CM",
    "alpha-3": "CMR",
    "numeric-code": 120,
    latitude: 6,
    longitude: 12,
  },
  {
    country: "Canada",
    "alpha-2": "CA",
    "alpha-3": "CAN",
    "numeric-code": 124,
    latitude: 60,
    longitude: -95,
  },
  {
    country: "Cape Verde",
    "alpha-2": "CV",
    "alpha-3": "CPV",
    "numeric-code": 132,
    latitude: 16,
    longitude: -24,
  },
  {
    country: "Cayman Islands",
    "alpha-2": "KY",
    "alpha-3": "CYM",
    "numeric-code": 136,
    latitude: 19.5,
    longitude: -80.5,
  },
  {
    country: "Central African Republic",
    "alpha-2": "CF",
    "alpha-3": "CAF",
    "numeric-code": 140,
    latitude: 7,
    longitude: 21,
  },
  {
    country: "Chad",
    "alpha-2": "TD",
    "alpha-3": "TCD",
    "numeric-code": 148,
    latitude: 15,
    longitude: 19,
  },
  {
    country: "Chile",
    "alpha-2": "CL",
    "alpha-3": "CHL",
    "numeric-code": 152,
    latitude: -30,
    longitude: -71,
  },
  {
    country: "China",
    "alpha-2": "CN",
    "alpha-3": "CHN",
    "numeric-code": 156,
    latitude: 35,
    longitude: 105,
  },
  {
    country: "Christmas Island",
    "alpha-2": "CX",
    "alpha-3": "CXR",
    "numeric-code": 162,
    latitude: -10.5,
    longitude: 105.6667,
  },
  {
    country: "Cocos (Keeling) Islands",
    "alpha-2": "CC",
    "alpha-3": "CCK",
    "numeric-code": 166,
    latitude: -12.5,
    longitude: 96.8333,
  },
  {
    country: "Colombia",
    "alpha-2": "CO",
    "alpha-3": "COL",
    "numeric-code": 170,
    latitude: 4,
    longitude: -72,
  },
  {
    country: "Comoros",
    "alpha-2": "KM",
    "alpha-3": "COM",
    "numeric-code": 174,
    latitude: -12.1667,
    longitude: 44.25,
  },
  {
    country: "Congo",
    "alpha-2": "CG",
    "alpha-3": "COG",
    "numeric-code": 178,
    latitude: -1,
    longitude: 15,
  },
  {
    country: "Democratic Republic of the Congo",
    "alpha-2": "CD",
    "alpha-3": "COD",
    "numeric-code": 180,
    latitude: 0,
    longitude: 25,
  },
  {
    country: "Cook Islands",
    "alpha-2": "CK",
    "alpha-3": "COK",
    "numeric-code": 184,
    latitude: -21.2333,
    longitude: -159.7667,
  },
  {
    country: "Costa Rica",
    "alpha-2": "CR",
    "alpha-3": "CRI",
    "numeric-code": 188,
    latitude: 10,
    longitude: -84,
  },
  {
    country: "Ivory Coast",
    "alpha-2": "CI",
    "alpha-3": "CIV",
    "numeric-code": 384,
    latitude: 8,
    longitude: -5,
  },
  {
    country: "Croatia",
    "alpha-2": "HR",
    "alpha-3": "HRV",
    "numeric-code": 191,
    latitude: 45.1667,
    longitude: 15.5,
  },
  {
    country: "Cuba",
    "alpha-2": "CU",
    "alpha-3": "CUB",
    "numeric-code": 192,
    latitude: 21.5,
    longitude: -80,
  },
  {
    country: "Cyprus",
    "alpha-2": "CY",
    "alpha-3": "CYP",
    "numeric-code": 196,
    latitude: 35,
    longitude: 33,
  },
  {
    country: "Czech Republic",
    "alpha-2": "CZ",
    "alpha-3": "CZE",
    "numeric-code": 203,
    latitude: 49.75,
    longitude: 15.5,
  },
  {
    country: "Denmark",
    "alpha-2": "DK",
    "alpha-3": "DNK",
    "numeric-code": 208,
    latitude: 56,
    longitude: 10,
  },
  {
    country: "Djibouti",
    "alpha-2": "DJ",
    "alpha-3": "DJI",
    "numeric-code": 262,
    latitude: 11.5,
    longitude: 43,
  },
  {
    country: "Dominica",
    "alpha-2": "DM",
    "alpha-3": "DMA",
    "numeric-code": 212,
    latitude: 15.4167,
    longitude: -61.3333,
  },
  {
    country: "Dominican Republic",
    "alpha-2": "DO",
    "alpha-3": "DOM",
    "numeric-code": 214,
    latitude: 19,
    longitude: -70.6667,
  },
  {
    country: "Ecuador",
    "alpha-2": "EC",
    "alpha-3": "ECU",
    "numeric-code": 218,
    latitude: -2,
    longitude: -77.5,
  },
  {
    country: "Egypt",
    "alpha-2": "EG",
    "alpha-3": "EGY",
    "numeric-code": 818,
    latitude: 27,
    longitude: 30,
  },
  {
    country: "El Salvador",
    "alpha-2": "SV",
    "alpha-3": "SLV",
    "numeric-code": 222,
    latitude: 13.8333,
    longitude: -88.9167,
  },
  {
    country: "Equatorial Guinea",
    "alpha-2": "GQ",
    "alpha-3": "GNQ",
    "numeric-code": 226,
    latitude: 2,
    longitude: 10,
  },
  {
    country: "Eritrea",
    "alpha-2": "ER",
    "alpha-3": "ERI",
    "numeric-code": 232,
    latitude: 15,
    longitude: 39,
  },
  {
    country: "Estonia",
    "alpha-2": "EE",
    "alpha-3": "EST",
    "numeric-code": 233,
    latitude: 59,
    longitude: 26,
  },
  {
    country: "Ethiopia",
    "alpha-2": "ET",
    "alpha-3": "ETH",
    "numeric-code": 231,
    latitude: 8,
    longitude: 38,
  },
  {
    country: "Falkland Islands",
    "alpha-2": "FK",
    "alpha-3": "FLK",
    "numeric-code": 238,
    latitude: -51.75,
    longitude: -59,
  },
  {
    country: "Faroe Islands",
    "alpha-2": "FO",
    "alpha-3": "FRO",
    "numeric-code": 234,
    latitude: 62,
    longitude: -7,
  },
  {
    country: "Fiji",
    "alpha-2": "FJ",
    "alpha-3": "FJI",
    "numeric-code": 242,
    latitude: -18,
    longitude: 175,
  },
  {
    country: "Finland",
    "alpha-2": "FI",
    "alpha-3": "FIN",
    "numeric-code": 246,
    latitude: 64,
    longitude: 26,
  },
  {
    country: "France",
    "alpha-2": "FR",
    "alpha-3": "FRA",
    "numeric-code": 250,
    latitude: 46,
    longitude: 2,
  },
  {
    country: "French Guiana",
    "alpha-2": "GF",
    "alpha-3": "GUF",
    "numeric-code": 254,
    latitude: 4,
    longitude: -53,
  },
  {
    country: "French Polynesia",
    "alpha-2": "PF",
    "alpha-3": "PYF",
    "numeric-code": 258,
    latitude: -15,
    longitude: -140,
  },
  {
    country: "French Southern Territories",
    "alpha-2": "TF",
    "alpha-3": "ATF",
    "numeric-code": 260,
    latitude: -43,
    longitude: 67,
  },
  {
    country: "Gabon",
    "alpha-2": "GA",
    "alpha-3": "GAB",
    "numeric-code": 266,
    latitude: -1,
    longitude: 11.75,
  },
  {
    country: "Gambia",
    "alpha-2": "GM",
    "alpha-3": "GMB",
    "numeric-code": 270,
    latitude: 13.4667,
    longitude: -16.5667,
  },
  {
    country: "Georgia",
    "alpha-2": "GE",
    "alpha-3": "GEO",
    "numeric-code": 268,
    latitude: 42,
    longitude: 43.5,
  },
  {
    country: "Germany",
    "alpha-2": "DE",
    "alpha-3": "DEU",
    "numeric-code": 276,
    latitude: 51,
    longitude: 9,
  },
  {
    country: "Ghana",
    "alpha-2": "GH",
    "alpha-3": "GHA",
    "numeric-code": 288,
    latitude: 8,
    longitude: -2,
  },
  {
    country: "Gibraltar",
    "alpha-2": "GI",
    "alpha-3": "GIB",
    "numeric-code": 292,
    latitude: 36.1833,
    longitude: -5.3667,
  },
  {
    country: "Greece",
    "alpha-2": "GR",
    "alpha-3": "GRC",
    "numeric-code": 300,
    latitude: 39,
    longitude: 22,
  },
  {
    country: "Greenland",
    "alpha-2": "GL",
    "alpha-3": "GRL",
    "numeric-code": 304,
    latitude: 72,
    longitude: -40,
  },
  {
    country: "Grenada",
    "alpha-2": "GD",
    "alpha-3": "GRD",
    "numeric-code": 308,
    latitude: 12.1167,
    longitude: -61.6667,
  },
  {
    country: "Guadeloupe",
    "alpha-2": "GP",
    "alpha-3": "GLP",
    "numeric-code": 312,
    latitude: 16.25,
    longitude: -61.5833,
  },
  {
    country: "Guam",
    "alpha-2": "GU",
    "alpha-3": "GUM",
    "numeric-code": 316,
    latitude: 13.4667,
    longitude: 144.7833,
  },
  {
    country: "Guatemala",
    "alpha-2": "GT",
    "alpha-3": "GTM",
    "numeric-code": 320,
    latitude: 15.5,
    longitude: -90.25,
  },
  {
    country: "Guernsey",
    "alpha-2": "GG",
    "alpha-3": "GGY",
    "numeric-code": 831,
    latitude: 49.5,
    longitude: -2.56,
  },
  {
    country: "Guinea",
    "alpha-2": "GN",
    "alpha-3": "GIN",
    "numeric-code": 324,
    latitude: 11,
    longitude: -10,
  },
  {
    country: "Guinea-Bissau",
    "alpha-2": "GW",
    "alpha-3": "GNB",
    "numeric-code": 624,
    latitude: 12,
    longitude: -15,
  },
  {
    country: "Guyana",
    "alpha-2": "GY",
    "alpha-3": "GUY",
    "numeric-code": 328,
    latitude: 5,
    longitude: -59,
  },
  {
    country: "Haiti",
    "alpha-2": "HT",
    "alpha-3": "HTI",
    "numeric-code": 332,
    latitude: 19,
    longitude: -72.4167,
  },
  {
    country: "Heard Island and McDonald Islands",
    "alpha-2": "HM",
    "alpha-3": "HMD",
    "numeric-code": 334,
    latitude: -53.1,
    longitude: 72.5167,
  },
  {
    country: "Vatican City",
    "alpha-2": "VA",
    "alpha-3": "VAT",
    "numeric-code": 336,
    latitude: 41.9,
    longitude: 12.45,
  },
  {
    country: "Honduras",
    "alpha-2": "HN",
    "alpha-3": "HND",
    "numeric-code": 340,
    latitude: 15,
    longitude: -86.5,
  },
  {
    country: "Hong Kong",
    "alpha-2": "HK",
    "alpha-3": "HKG",
    "numeric-code": 344,
    latitude: 22.25,
    longitude: 114.1667,
  },
  {
    country: "Hungary",
    "alpha-2": "HU",
    "alpha-3": "HUN",
    "numeric-code": 348,
    latitude: 47,
    longitude: 20,
  },
  {
    country: "Iceland",
    "alpha-2": "IS",
    "alpha-3": "ISL",
    "numeric-code": 352,
    latitude: 65,
    longitude: -18,
  },
  {
    country: "India",
    "alpha-2": "IN",
    "alpha-3": "IND",
    "numeric-code": 356,
    latitude: 20,
    longitude: 77,
  },
  {
    country: "Indonesia",
    "alpha-2": "ID",
    "alpha-3": "IDN",
    "numeric-code": 360,
    latitude: -5,
    longitude: 120,
  },
  {
    country: "Iran",
    "alpha-2": "IR",
    "alpha-3": "IRN",
    "numeric-code": 364,
    latitude: 32,
    longitude: 53,
  },
  {
    country: "Iraq",
    "alpha-2": "IQ",
    "alpha-3": "IRQ",
    "numeric-code": 368,
    latitude: 33,
    longitude: 44,
  },
  {
    country: "Ireland",
    "alpha-2": "IE",
    "alpha-3": "IRL",
    "numeric-code": 372,
    latitude: 53,
    longitude: -8,
  },
  {
    country: "Isle of Man",
    "alpha-2": "IM",
    "alpha-3": "IMN",
    "numeric-code": 833,
    latitude: 54.23,
    longitude: -4.55,
  },
  {
    country: "Israel",
    "alpha-2": "IL",
    "alpha-3": "ISR",
    "numeric-code": 376,
    latitude: 31.5,
    longitude: 34.75,
  },
  {
    country: "Italy",
    "alpha-2": "IT",
    "alpha-3": "ITA",
    "numeric-code": 380,
    latitude: 42.8333,
    longitude: 12.8333,
  },
  {
    country: "Jamaica",
    "alpha-2": "JM",
    "alpha-3": "JAM",
    "numeric-code": 388,
    latitude: 18.25,
    longitude: -77.5,
  },
  {
    country: "Japan",
    "alpha-2": "JP",
    "alpha-3": "JPN",
    "numeric-code": 392,
    latitude: 36,
    longitude: 138,
  },
  {
    country: "Jersey",
    "alpha-2": "JE",
    "alpha-3": "JEY",
    "numeric-code": 832,
    latitude: 49.21,
    longitude: -2.13,
  },
  {
    country: "Jordan",
    "alpha-2": "JO",
    "alpha-3": "JOR",
    "numeric-code": 400,
    latitude: 31,
    longitude: 36,
  },
  {
    country: "Kazakhstan",
    "alpha-2": "KZ",
    "alpha-3": "KAZ",
    "numeric-code": 398,
    latitude: 48,
    longitude: 68,
  },
  {
    country: "Kenya",
    "alpha-2": "KE",
    "alpha-3": "KEN",
    "numeric-code": 404,
    latitude: 1,
    longitude: 38,
  },
  {
    country: "Kiribati",
    "alpha-2": "KI",
    "alpha-3": "KIR",
    "numeric-code": 296,
    latitude: 1.4167,
    longitude: 173,
  },
  {
    country: "North Korea",
    "alpha-2": "KP",
    "alpha-3": "PRK",
    "numeric-code": 408,
    latitude: 40,
    longitude: 127,
  },
  {
    country: "South Korea",
    "alpha-2": "KR",
    "alpha-3": "KOR",
    "numeric-code": 410,
    latitude: 37,
    longitude: 127.5,
  },
  {
    country: "Kuwait",
    "alpha-2": "KW",
    "alpha-3": "KWT",
    "numeric-code": 414,
    latitude: 29.3375,
    longitude: 47.6581,
  },
  {
    country: "Kyrgyzstan",
    "alpha-2": "KG",
    "alpha-3": "KGZ",
    "numeric-code": 417,
    latitude: 41,
    longitude: 75,
  },
  {
    country: "Laos",
    "alpha-2": "LA",
    "alpha-3": "LAO",
    "numeric-code": 418,
    latitude: 18,
    longitude: 105,
  },
  {
    country: "Latvia",
    "alpha-2": "LV",
    "alpha-3": "LVA",
    "numeric-code": 428,
    latitude: 57,
    longitude: 25,
  },
  {
    country: "Lebanon",
    "alpha-2": "LB",
    "alpha-3": "LBN",
    "numeric-code": 422,
    latitude: 33.8333,
    longitude: 35.8333,
  },
  {
    country: "Lesotho",
    "alpha-2": "LS",
    "alpha-3": "LSO",
    "numeric-code": 426,
    latitude: -29.5,
    longitude: 28.5,
  },
  {
    country: "Liberia",
    "alpha-2": "LR",
    "alpha-3": "LBR",
    "numeric-code": 430,
    latitude: 6.5,
    longitude: -9.5,
  },
  {
    country: "Libya",
    "alpha-2": "LY",
    "alpha-3": "LBY",
    "numeric-code": 434,
    latitude: 25,
    longitude: 17,
  },
  {
    country: "Liechtenstein",
    "alpha-2": "LI",
    "alpha-3": "LIE",
    "numeric-code": 438,
    latitude: 47.1667,
    longitude: 9.5333,
  },
  {
    country: "Lithuania",
    "alpha-2": "LT",
    "alpha-3": "LTU",
    "numeric-code": 440,
    latitude: 56,
    longitude: 24,
  },
  {
    country: "Luxembourg",
    "alpha-2": "LU",
    "alpha-3": "LUX",
    "numeric-code": 442,
    latitude: 49.75,
    longitude: 6.1667,
  },
  {
    country: "Macau",
    "alpha-2": "MO",
    "alpha-3": "MAC",
    "numeric-code": 446,
    latitude: 22.1667,
    longitude: 113.55,
  },
  {
    country: "North Macedonia",
    "alpha-2": "MK",
    "alpha-3": "MKD",
    "numeric-code": 807,
    latitude: 41.8333,
    longitude: 22,
  },
  {
    country: "Madagascar",
    "alpha-2": "MG",
    "alpha-3": "MDG",
    "numeric-code": 450,
    latitude: -20,
    longitude: 47,
  },
  {
    country: "Malawi",
    "alpha-2": "MW",
    "alpha-3": "MWI",
    "numeric-code": 454,
    latitude: -13.5,
    longitude: 34,
  },
  {
    country: "Malaysia",
    "alpha-2": "MY",
    "alpha-3": "MYS",
    "numeric-code": 458,
    latitude: 2.5,
    longitude: 112.5,
  },
  {
    country: "Maldives",
    "alpha-2": "MV",
    "alpha-3": "MDV",
    "numeric-code": 462,
    latitude: 3.25,
    longitude: 73,
  },
  {
    country: "Mali",
    "alpha-2": "ML",
    "alpha-3": "MLI",
    "numeric-code": 466,
    latitude: 17,
    longitude: -4,
  },
  {
    country: "Malta",
    "alpha-2": "MT",
    "alpha-3": "MLT",
    "numeric-code": 470,
    latitude: 35.8333,
    longitude: 14.5833,
  },
  {
    country: "Marshall Islands",
    "alpha-2": "MH",
    "alpha-3": "MHL",
    "numeric-code": 584,
    latitude: 9,
    longitude: 168,
  },
  {
    country: "Martinique",
    "alpha-2": "MQ",
    "alpha-3": "MTQ",
    "numeric-code": 474,
    latitude: 14.6667,
    longitude: -61,
  },
  {
    country: "Mauritania",
    "alpha-2": "MR",
    "alpha-3": "MRT",
    "numeric-code": 478,
    latitude: 20,
    longitude: -12,
  },
  {
    country: "Mauritius",
    "alpha-2": "MU",
    "alpha-3": "MUS",
    "numeric-code": 480,
    latitude: -20.2833,
    longitude: 57.55,
  },
  {
    country: "Mayotte",
    "alpha-2": "YT",
    "alpha-3": "MYT",
    "numeric-code": 175,
    latitude: -12.8333,
    longitude: 45.1667,
  },
  {
    country: "Mexico",
    "alpha-2": "MX",
    "alpha-3": "MEX",
    "numeric-code": 484,
    latitude: 23,
    longitude: -102,
  },
  {
    country: "Micronesia",
    "alpha-2": "FM",
    "alpha-3": "FSM",
    "numeric-code": 583,
    latitude: 6.9167,
    longitude: 158.25,
  },
  {
    country: "Moldova",
    "alpha-2": "MD",
    "alpha-3": "MDA",
    "numeric-code": 498,
    latitude: 47,
    longitude: 29,
  },
  {
    country: "Monaco",
    "alpha-2": "MC",
    "alpha-3": "MCO",
    "numeric-code": 492,
    latitude: 43.7333,
    longitude: 7.4,
  },
  {
    country: "Mongolia",
    "alpha-2": "MN",
    "alpha-3": "MNG",
    "numeric-code": 496,
    latitude: 46,
    longitude: 105,
  },
  {
    country: "Montenegro",
    "alpha-2": "ME",
    "alpha-3": "MNE",
    "numeric-code": 499,
    latitude: 42,
    longitude: 19,
  },
  {
    country: "Montserrat",
    "alpha-2": "MS",
    "alpha-3": "MSR",
    "numeric-code": 500,
    latitude: 16.75,
    longitude: -62.2,
  },
  {
    country: "Morocco",
    "alpha-2": "MA",
    "alpha-3": "MAR",
    "numeric-code": 504,
    latitude: 32,
    longitude: -5,
  },
  {
    country: "Mozambique",
    "alpha-2": "MZ",
    "alpha-3": "MOZ",
    "numeric-code": 508,
    latitude: -18.25,
    longitude: 35,
  },
  {
    country: "Myanmar",
    "alpha-2": "MM",
    "alpha-3": "MMR",
    "numeric-code": 104,
    latitude: 22,
    longitude: 98,
  },
  {
    country: "Namibia",
    "alpha-2": "NA",
    "alpha-3": "NAM",
    "numeric-code": 516,
    latitude: -22,
    longitude: 17,
  },
  {
    country: "Nauru",
    "alpha-2": "NR",
    "alpha-3": "NRU",
    "numeric-code": 520,
    latitude: -0.5333,
    longitude: 166.9167,
  },
  {
    country: "Nepal",
    "alpha-2": "NP",
    "alpha-3": "NPL",
    "numeric-code": 524,
    latitude: 28,
    longitude: 84,
  },
  {
    country: "Netherlands",
    "alpha-2": "NL",
    "alpha-3": "NLD",
    "numeric-code": 528,
    latitude: 52.5,
    longitude: 5.75,
  },
  {
    country: "Netherlands Antilles",
    "alpha-2": "AN",
    "alpha-3": "ANT",
    "numeric-code": 530,
    latitude: 12.25,
    longitude: -68.75,
  },
  {
    country: "New Caledonia",
    "alpha-2": "NC",
    "alpha-3": "NCL",
    "numeric-code": 540,
    latitude: -21.5,
    longitude: 165.5,
  },
  {
    country: "New Zealand",
    "alpha-2": "NZ",
    "alpha-3": "NZL",
    "numeric-code": 554,
    latitude: -41,
    longitude: 174,
  },
  {
    country: "Nicaragua",
    "alpha-2": "NI",
    "alpha-3": "NIC",
    "numeric-code": 558,
    latitude: 13,
    longitude: -85,
  },
  {
    country: "Niger",
    "alpha-2": "NE",
    "alpha-3": "NER",
    "numeric-code": 562,
    latitude: 16,
    longitude: 8,
  },
  {
    country: "Nigeria",
    "alpha-2": "NG",
    "alpha-3": "NGA",
    "numeric-code": 566,
    latitude: 10,
    longitude: 8,
  },
  {
    country: "Niue",
    "alpha-2": "NU",
    "alpha-3": "NIU",
    "numeric-code": 570,
    latitude: -19.0333,
    longitude: -169.8667,
  },
  {
    country: "Norfolk Island",
    "alpha-2": "NF",
    "alpha-3": "NFK",
    "numeric-code": 574,
    latitude: -29.0333,
    longitude: 167.95,
  },
  {
    country: "Northern Mariana Islands",
    "alpha-2": "MP",
    "alpha-3": "MNP",
    "numeric-code": 580,
    latitude: 15.2,
    longitude: 145.75,
  },
  {
    country: "Norway",
    "alpha-2": "NO",
    "alpha-3": "NOR",
    "numeric-code": 578,
    latitude: 62,
    longitude: 10,
  },
  {
    country: "Oman",
    "alpha-2": "OM",
    "alpha-3": "OMN",
    "numeric-code": 512,
    latitude: 21,
    longitude: 57,
  },
  {
    country: "Pakistan",
    "alpha-2": "PK",
    "alpha-3": "PAK",
    "numeric-code": 586,
    latitude: 30,
    longitude: 70,
  },
  {
    country: "Palau",
    "alpha-2": "PW",
    "alpha-3": "PLW",
    "numeric-code": 585,
    latitude: 7.5,
    longitude: 134.5,
  },
  {
    country: "Palestine",
    "alpha-2": "PS",
    "alpha-3": "PSE",
    "numeric-code": 275,
    latitude: 32,
    longitude: 35.25,
  },
  {
    country: "Panama",
    "alpha-2": "PA",
    "alpha-3": "PAN",
    "numeric-code": 591,
    latitude: 9,
    longitude: -80,
  },
  {
    country: "Papua New Guinea",
    "alpha-2": "PG",
    "alpha-3": "PNG",
    "numeric-code": 598,
    latitude: -6,
    longitude: 147,
  },
  {
    country: "Paraguay",
    "alpha-2": "PY",
    "alpha-3": "PRY",
    "numeric-code": 600,
    latitude: -23,
    longitude: -58,
  },
  {
    country: "Peru",
    "alpha-2": "PE",
    "alpha-3": "PER",
    "numeric-code": 604,
    latitude: -10,
    longitude: -76,
  },
  {
    country: "Philippines",
    "alpha-2": "PH",
    "alpha-3": "PHL",
    "numeric-code": 608,
    latitude: 13,
    longitude: 122,
  },
  {
    country: "Pitcairn",
    "alpha-2": "PN",
    "alpha-3": "PCN",
    "numeric-code": 612,
    latitude: -24.7,
    longitude: -127.4,
  },
  {
    country: "Poland",
    "alpha-2": "PL",
    "alpha-3": "POL",
    "numeric-code": 616,
    latitude: 52,
    longitude: 20,
  },
  {
    country: "Portugal",
    "alpha-2": "PT",
    "alpha-3": "PRT",
    "numeric-code": 620,
    latitude: 39.5,
    longitude: -8,
  },
  {
    country: "Puerto Rico",
    "alpha-2": "PR",
    "alpha-3": "PRI",
    "numeric-code": 630,
    latitude: 18.25,
    longitude: -66.5,
  },
  {
    country: "Qatar",
    "alpha-2": "QA",
    "alpha-3": "QAT",
    "numeric-code": 634,
    latitude: 25.5,
    longitude: 51.25,
  },
  {
    country: "Réunion",
    "alpha-2": "RE",
    "alpha-3": "REU",
    "numeric-code": 638,
    latitude: -21.1,
    longitude: 55.6,
  },
  {
    country: "Romania",
    "alpha-2": "RO",
    "alpha-3": "ROU",
    "numeric-code": 642,
    latitude: 46,
    longitude: 25,
  },
  {
    country: "Russia",
    "alpha-2": "RU",
    "alpha-3": "RUS",
    "numeric-code": 643,
    latitude: 60,
    longitude: 100,
  },
  {
    country: "Rwanda",
    "alpha-2": "RW",
    "alpha-3": "RWA",
    "numeric-code": 646,
    latitude: -2,
    longitude: 30,
  },
  {
    country: "Saint Helena",
    "alpha-2": "SH",
    "alpha-3": "SHN",
    "numeric-code": 654,
    latitude: -15.9333,
    longitude: -5.7,
  },
  {
    country: "Saint Kitts and Nevis",
    "alpha-2": "KN",
    "alpha-3": "KNA",
    "numeric-code": 659,
    latitude: 17.3333,
    longitude: -62.75,
  },
  {
    country: "Saint Lucia",
    "alpha-2": "LC",
    "alpha-3": "LCA",
    "numeric-code": 662,
    latitude: 13.8833,
    longitude: -61.1333,
  },
  {
    country: "Saint Pierre and Miquelon",
    "alpha-2": "PM",
    "alpha-3": "SPM",
    "numeric-code": 666,
    latitude: 46.8333,
    longitude: -56.3333,
  },
  {
    country: "Saint Vincent and the Grenadines",
    "alpha-2": "VC",
    "alpha-3": "VCT",
    "numeric-code": 670,
    latitude: 13.25,
    longitude: -61.2,
  },
  {
    country: "Samoa",
    "alpha-2": "WS",
    "alpha-3": "WSM",
    "numeric-code": 882,
    latitude: -13.5833,
    longitude: -172.3333,
  },
  {
    country: "San Marino",
    "alpha-2": "SM",
    "alpha-3": "SMR",
    "numeric-code": 674,
    latitude: 43.7667,
    longitude: 12.4167,
  },
  {
    country: "São Tomé and Príncipe",
    "alpha-2": "ST",
    "alpha-3": "STP",
    "numeric-code": 678,
    latitude: 1,
    longitude: 7,
  },
  {
    country: "Saudi Arabia",
    "alpha-2": "SA",
    "alpha-3": "SAU",
    "numeric-code": 682,
    latitude: 25,
    longitude: 45,
  },
  {
    country: "Senegal",
    "alpha-2": "SN",
    "alpha-3": "SEN",
    "numeric-code": 686,
    latitude: 14,
    longitude: -14,
  },
  {
    country: "Serbia",
    "alpha-2": "RS",
    "alpha-3": "SRB",
    "numeric-code": 688,
    latitude: 44,
    longitude: 21,
  },
  {
    country: "Seychelles",
    "alpha-2": "SC",
    "alpha-3": "SYC",
    "numeric-code": 690,
    latitude: -4.5833,
    longitude: 55.6667,
  },
  {
    country: "Sierra Leone",
    "alpha-2": "SL",
    "alpha-3": "SLE",
    "numeric-code": 694,
    latitude: 8.5,
    longitude: -11.5,
  },
  {
    country: "Singapore",
    "alpha-2": "SG",
    "alpha-3": "SGP",
    "numeric-code": 702,
    latitude: 1.3667,
    longitude: 103.8,
  },
  {
    country: "Slovakia",
    "alpha-2": "SK",
    "alpha-3": "SVK",
    "numeric-code": 703,
    latitude: 48.6667,
    longitude: 19.5,
  },
  {
    country: "Slovenia",
    "alpha-2": "SI",
    "alpha-3": "SVN",
    "numeric-code": 705,
    latitude: 46,
    longitude: 15,
  },
  {
    country: "Solomon Islands",
    "alpha-2": "SB",
    "alpha-3": "SLB",
    "numeric-code": 90,
    latitude: -8,
    longitude: 159,
  },
  {
    country: "Somalia",
    "alpha-2": "SO",
    "alpha-3": "SOM",
    "numeric-code": 706,
    latitude: 10,
    longitude: 49,
  },
  {
    country: "South Africa",
    "alpha-2": "ZA",
    "alpha-3": "ZAF",
    "numeric-code": 710,
    latitude: -29,
    longitude: 24,
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    "alpha-2": "GS",
    "alpha-3": "SGS",
    "numeric-code": 239,
    latitude: -54.5,
    longitude: -37,
  },
  {
    country: "South Sudan",
    "alpha-2": "SS",
    "alpha-3": "SSD",
    "numeric-code": 728,
    latitude: 8,
    longitude: 30,
  },
  {
    country: "Spain",
    "alpha-2": "ES",
    "alpha-3": "ESP",
    "numeric-code": 724,
    latitude: 40,
    longitude: -4,
  },
  {
    country: "Sri Lanka",
    "alpha-2": "LK",
    "alpha-3": "LKA",
    "numeric-code": 144,
    latitude: 7,
    longitude: 81,
  },
  {
    country: "Sudan",
    "alpha-2": "SD",
    "alpha-3": "SDN",
    "numeric-code": 736,
    latitude: 15,
    longitude: 30,
  },
  {
    country: "Suriname",
    "alpha-2": "SR",
    "alpha-3": "SUR",
    "numeric-code": 740,
    latitude: 4,
    longitude: -56,
  },
  {
    country: "Svalbard and Jan Mayen",
    "alpha-2": "SJ",
    "alpha-3": "SJM",
    "numeric-code": 744,
    latitude: 78,
    longitude: 20,
  },
  {
    country: "Eswatini",
    "alpha-2": "SZ",
    "alpha-3": "SWZ",
    "numeric-code": 748,
    latitude: -26.5,
    longitude: 31.5,
  },
  {
    country: "Sweden",
    "alpha-2": "SE",
    "alpha-3": "SWE",
    "numeric-code": 752,
    latitude: 62,
    longitude: 15,
  },
  {
    country: "Switzerland",
    "alpha-2": "CH",
    "alpha-3": "CHE",
    "numeric-code": 756,
    latitude: 47,
    longitude: 8,
  },
  {
    country: "Syria",
    "alpha-2": "SY",
    "alpha-3": "SYR",
    "numeric-code": 760,
    latitude: 35,
    longitude: 38,
  },
  {
    country: "Taiwan",
    "alpha-2": "TW",
    "alpha-3": "TWN",
    "numeric-code": 158,
    latitude: 23.5,
    longitude: 121,
  },
  {
    country: "Tajikistan",
    "alpha-2": "TJ",
    "alpha-3": "TJK",
    "numeric-code": 762,
    latitude: 39,
    longitude: 71,
  },
  {
    country: "Tanzania",
    "alpha-2": "TZ",
    "alpha-3": "TZA",
    "numeric-code": 834,
    latitude: -6,
    longitude: 35,
  },
  {
    country: "Thailand",
    "alpha-2": "TH",
    "alpha-3": "THA",
    "numeric-code": 764,
    latitude: 15,
    longitude: 100,
  },
  {
    country: "Timor-Leste",
    "alpha-2": "TL",
    "alpha-3": "TLS",
    "numeric-code": 626,
    latitude: -8.55,
    longitude: 125.5167,
  },
  {
    country: "Togo",
    "alpha-2": "TG",
    "alpha-3": "TGO",
    "numeric-code": 768,
    latitude: 8,
    longitude: 1.1667,
  },
  {
    country: "Tokelau",
    "alpha-2": "TK",
    "alpha-3": "TKL",
    "numeric-code": 772,
    latitude: -9,
    longitude: -172,
  },
  {
    country: "Tonga",
    "alpha-2": "TO",
    "alpha-3": "TON",
    "numeric-code": 776,
    latitude: -20,
    longitude: -175,
  },
  {
    country: "Trinidad and Tobago",
    "alpha-2": "TT",
    "alpha-3": "TTO",
    "numeric-code": 780,
    latitude: 11,
    longitude: -61,
  },
  {
    country: "Tunisia",
    "alpha-2": "TN",
    "alpha-3": "TUN",
    "numeric-code": 788,
    latitude: 34,
    longitude: 9,
  },
  {
    country: "Turkey",
    "alpha-2": "TR",
    "alpha-3": "TUR",
    "numeric-code": 792,
    latitude: 39,
    longitude: 35,
  },
  {
    country: "Turkmenistan",
    "alpha-2": "TM",
    "alpha-3": "TKM",
    "numeric-code": 795,
    latitude: 40,
    longitude: 60,
  },
  {
    country: "Turks and Caicos Islands",
    "alpha-2": "TC",
    "alpha-3": "TCA",
    "numeric-code": 796,
    latitude: 21.75,
    longitude: -71.5833,
  },
  {
    country: "Tuvalu",
    "alpha-2": "TV",
    "alpha-3": "TUV",
    "numeric-code": 798,
    latitude: -8,
    longitude: 178,
  },
  {
    country: "Uganda",
    "alpha-2": "UG",
    "alpha-3": "UGA",
    "numeric-code": 800,
    latitude: 1,
    longitude: 32,
  },
  {
    country: "Ukraine",
    "alpha-2": "UA",
    "alpha-3": "UKR",
    "numeric-code": 804,
    latitude: 49,
    longitude: 32,
  },
  {
    country: "United Arab Emirates",
    "alpha-2": "AE",
    "alpha-3": "ARE",
    "numeric-code": 784,
    latitude: 24,
    longitude: 54,
  },
  {
    country: "United Kingdom",
    "alpha-2": "GB",
    "alpha-3": "GBR",
    "numeric-code": 826,
    latitude: 54,
    longitude: -2,
  },
  {
    country: "United States",
    "alpha-2": "US",
    "alpha-3": "USA",
    "numeric-code": 840,
    latitude: 38,
    longitude: -97,
  },
  {
    country: "United States Minor Outlying Islands",
    "alpha-2": "UM",
    "alpha-3": "UMI",
    "numeric-code": 581,
    latitude: 19.2833,
    longitude: 166.6,
  },
  {
    country: "Uruguay",
    "alpha-2": "UY",
    "alpha-3": "URY",
    "numeric-code": 858,
    latitude: -33,
    longitude: -56,
  },
  {
    country: "Uzbekistan",
    "alpha-2": "UZ",
    "alpha-3": "UZB",
    "numeric-code": 860,
    latitude: 41,
    longitude: 64,
  },
  {
    country: "Vanuatu",
    "alpha-2": "VU",
    "alpha-3": "VUT",
    "numeric-code": 548,
    latitude: -16,
    longitude: 167,
  },
  {
    country: "Venezuela",
    "alpha-2": "VE",
    "alpha-3": "VEN",
    "numeric-code": 862,
    latitude: 8,
    longitude: -66,
  },
  {
    country: "Vietnam",
    "alpha-2": "VN",
    "alpha-3": "VNM",
    "numeric-code": 704,
    latitude: 16,
    longitude: 106,
  },
  {
    country: "Virgin Islands, British",
    "alpha-2": "VG",
    "alpha-3": "VGB",
    "numeric-code": 92,
    latitude: 18.5,
    longitude: -64.5,
  },
  {
    country: "Virgin Islands, U.S.",
    "alpha-2": "VI",
    "alpha-3": "VIR",
    "numeric-code": 850,
    latitude: 18.3333,
    longitude: -64.8333,
  },
  {
    country: "Wallis and Futuna",
    "alpha-2": "WF",
    "alpha-3": "WLF",
    "numeric-code": 876,
    latitude: -13.3,
    longitude: -176.2,
  },
  {
    country: "Western Sahara",
    "alpha-2": "EH",
    "alpha-3": "ESH",
    "numeric-code": 732,
    latitude: 24.5,
    longitude: -13,
  },
  {
    country: "Yemen",
    "alpha-2": "YE",
    "alpha-3": "YEM",
    "numeric-code": 887,
    latitude: 15,
    longitude: 48,
  },
  {
    country: "Zambia",
    "alpha-2": "ZM",
    "alpha-3": "ZMB",
    "numeric-code": 894,
    latitude: -15,
    longitude: 30,
  },
  {
    country: "Zimbabwe",
    "alpha-2": "ZW",
    "alpha-3": "ZWE",
    "numeric-code": 716,
    latitude: -20,
    longitude: 30,
  },
];

export const getAllCountryNames = (): string[] => {
  return COUNTRIES.map((c) => c.country);
};

// takes an arbitrary country name and returns the normalized version to match the countryMap above.
// If no match in countryMap, return null.
// Useful for AI-generated country names that may not be in the exact format as the countryMap.
export function getNormalizedCountryName(country: string): string | undefined {
  const normalized = COUNTRIES.find((c) =>
    isLikelySameString(c.country, country)
  );
  return normalized?.country ?? undefined;
}

export function getCountryInfo(country: string): Country | undefined {
  const normalized = getNormalizedCountryName(country);
  if (!normalized) return undefined;
  return COUNTRIES.find(
    (c) => c.country.toLowerCase() === normalized.toLowerCase()
  );
}
