import { useCallback, useEffect, useState } from "react";

// Narrative outbreak forecasts generated by the DeepSeek "generate-ai-predictions"
// edge function from the last 30 days of real outbreak signals. Each prediction
// is a written, descriptive forecast — e.g. "Given 3,000 cases with medium
// severity and ongoing transmission, forecast 4,500–5,000 total cases by late
// June, driven by seasonal patterns and potential H5N1 co-circulation."
export interface AIPrediction {
  disease: string;
  location: string;
  type: string; // "Case Forecast" | "Geographic Spread" | "Risk Assessment" | "Timeline Projection"
  prediction: string; // the narrative text
  confidence: number; // 0..100
  riskLevel: "low" | "medium" | "high" | "critical";
  targetDate: string; // "Jun 28, 2026"
  color: string;
}

export interface UseAIPredictionsResult {
  predictions: AIPrediction[];
  loading: boolean;
  error: string | null;
  cached: boolean;
  generatedAt: Date | null;
  signalCount: number | null;
  refresh: () => void;
  regenerate: () => void; // forces a fresh DeepSeek run (bypasses 24h cache)
}

export function useAIPredictions(): UseAIPredictionsResult {
  const [predictions, setPredictions] = useState<AIPrediction[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [cached, setCached] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);
  const [signalCount, setSignalCount] = useState<number | null>(null);
  const [nonce, setNonce] = useState(0);
  const [forceRefresh, setForceRefresh] = useState(false);

  const refresh = useCallback(() => {
    setForceRefresh(false);
    setNonce((n) => n + 1);
  }, []);
  const regenerate = useCallback(() => {
    setForceRefresh(true);
    setNonce((n) => n + 1);
  }, []);

  useEffect(() => {
    let active = true;
    async function load() {
      try {
        setLoading(true);
        setError(null);
        const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
        const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
        if (!supabaseUrl || !supabaseKey) throw new Error("Missing LiveHealth+ database configuration");

        const url = `${supabaseUrl}/functions/v1/generate-ai-predictions${
          forceRefresh ? "?refresh=true" : ""
        }`;
        const res = await fetch(url, {
          method: "GET",
          headers: {
            Authorization: `Bearer ${supabaseKey}`,
            "Content-Type": "application/json",
          },
        });
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData.error || `Failed to fetch predictions: ${res.statusText}`);
        }
        const data = await res.json();

        if (!active) return;

        if (data.error) {
          setError(
            String(data.error).includes("DEEPSEEK_API_KEY")
              ? "The DeepSeek API key isn't configured for this environment, so live AI forecasts can't be generated."
              : data.error
          );
          setPredictions([]);
          setCached(false);
        } else if (Array.isArray(data.predictions)) {
          // Drop unusable cards: forecasts for an unclassified "OTHER"/"Unknown"
          // disease can't be acted on. (The model occasionally also undershoots
          // already-reported totals — those we flag in the UI, not here, since we
          // can't reliably parse free-text figures.)
          const cleaned = (data.predictions as AIPrediction[]).filter((p) => {
            const d = (p.disease || "").trim().toUpperCase();
            return d && d !== "OTHER" && d !== "UNKNOWN" && d !== "UNKNOWN DISEASE";
          });
          setPredictions(cleaned);
          setCached(data.cached === true);
          setGeneratedAt(data.generatedAt ? new Date(data.generatedAt) : new Date());
          setSignalCount(typeof data.signalCount === "number" ? data.signalCount : null);
          setError(null);
        } else {
          setPredictions([]);
          setError("Unexpected response format from the prediction service.");
        }
      } catch (e: any) {
        if (!active) return;
        console.error("useAIPredictions error:", e);
        setError(e?.message || "Failed to load predictions");
        setPredictions([]);
      } finally {
        if (active) setLoading(false);
      }
    }
    load();
    return () => {
      active = false;
    };
  }, [nonce, forceRefresh]);

  return { predictions, loading, error, cached, generatedAt, signalCount, refresh, regenerate };
}
